var CONFIG = {};

CONFIG.opt = {  "编辑": "btn-warning edit",
				"浏览": "scan",
				"提交": "btn-success submit",
				"删除": "btn-danger delete",
				"锁定": "btn-danger lock",
				"解锁": "btn-danger unlock",
				"对账": "btn-danger checkBill",
				"送货": "btn-primary send",
				"驳回": "btn-danger reject",
				"核销": "btn-warning check",
				"核完": "btn-success over",
				"绑定": "btn-success bind",
				"解绑": "btn-warning unbind",
				"重新调用": "btn-danger reInvoke",
				"重新处理": "btn-warning reDeal",
				"打印": "print",
				"重置": "btn-warning reset",
				"下载": "btn-warning download",
				"处理": "btn-warning deal",
				"打印拣货单": "printPick",
				"收货": "btn-success receive",
				"拆分": "btn-success split",
				"分摊": "btn-success share",
				"分配": "btn-success divide",
				"跟进": "btn-danger follow",
				"保存": "btn-success save",
				"认证": "btn-danger approve",
				"复制": "btn-info copy",
				"飞单": "btn-warning flyOrder"
			};